Python 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> import turtle
>>> turtle.penup()
>>> turtle.goto(-300,100)
>>> turtle.goto(-300,150)
>>> turtle.pendown()
>>> turtle.forward(50)
>>> turtle.penup()
>>> turtle.goto(-250,100)
>>> turtle.goto(-450,100)
>>> turtle.goto(-350,100)
>>> turtle.pendown()
>>> turtle.forward(100)
>>> turtle.forward(50)
>>> 4
4
>>> turtle.penup()
>>> turtle.goto (-300,50)
>>> turtle.pendown()
>>> turtle.circle(50)
>>> turtle.undo()
>>> turtle.right(180)
>>> turtle.undo
<function undo at 0x000002126D064550>
>>> turtle.undo()
>>> turtle.undo()
>>> turtle.undo()
>>> turtle.goto(-300,30)
>>> turtle.pendown()
>>> turtle.right(90)
>>> turtle.circle(50)
>>> turtle.penup()
>>> turtle.goto(-300,-100)
>>> turtle.goto(-300,-80)
>>> turtle.left(90)
>>> turtle.forward(100)
>>> turtle.undo()
>>> turtle.pendown()
>>> turtle.forward(100)
>>> turtle.backward(50)
>>> turtle.left(90)
>>> turtle.forward(20)
>>> turtle.penup()
>>> turtle.goto(-300,-100)
>>> turtle.right(180)
>>> turtle.circle(50)
>>> turtle.forward(20)
>>> turtle.forward(30)
>>> turtle.pendown()
>>> turtle.circle(50)
>>> turtle.penup()
>>> turtle.goto(-150,100)
>>> turtle.left(90)
>>> turtle.forward(50)
>>> turtle.right(90)
>>> turtle.circle(80)
>>> turtle.pendown()
>>> turtle.circle(80)
>>> turtle.goto(-50,100)
>>> turtle.undo()
>>> turtle.penup()
>>> turtle.goto(100,100)
>>> turtle.left(90)
>>> turtle.pendown()
>>> turtle.forward(4)
>>> turtle.forwarad(40)
Traceback (most recent call last):
  File "<pyshell#62>", line 1, in <module>
    turtle.forwarad(40)
AttributeError: module 'turtle' has no attribute 'forwarad'
>>> turtle.forward(40)
>>> turtle.penup()
>>> turtle.goto(100,70)
>>> turtle.pendown()
>>> turtle.forward(40)
>>> turtle.forward(4)
>>> turtle.penup()
>>> turtle.goto(144,130)
>>> turtle.right(90)
>>> turtle.pendown()
>>> turtle.forward(200)
>>> turtle.ubdo
Traceback (most recent call last):
  File "<pyshell#74>", line 1, in <module>
    turtle.ubdo
AttributeError: module 'turtle' has no attribute 'ubdo'
>>> turtle.undo()
>>> turtle.forward(150)
>>> turtle.penup()
>>> turtle.goto(160,130)
>>> turtle.pendown()
>>> turtle.forward(200)
>>> turtle.penup()
>>> turtle.goto(200,130)
>>> turtle.pendown()
>>> turtle.forward(150)
>>> turtle.left(90)
>>> turtle.forward(150)
>>> turtle.penup()
>>> turtle.goto (270,130)
>>> turtle.forward(100)
>>> turtle.right(50)
>>> turtle.right(40)
>>> turtle.pendown()
>>> turtle.forward(170)
>>> turtle.backward(85)
>>> turtle.left(90)
>>> turtle.forward(30)
>>>turtle.exitonclick()
